### ISSUE TITLE
Observation messages time resolution

### ISSUE THREAD

**Issue by KaraMelih** [SNEWS2/SNEWS_Publishing_Tools#12]
I cannot fully recall the consensus on the time resolution; currently, we are using `"%H:%M:%S:%f"` which is up to 6 digits on the floating-point, therefore, has a few ms resolutions. There were discussions about using 64 bits or two time strings where the latter indicates ns after seconds.<br>

Let's keep this issue to track.

**Comment by KaraMelih** [comment]
Also related to this issue; #10.

**Comment by KaraMelih** [comment]
snews has not set time format/resolution yet.

**Comment by joesmolsky** [comment]
Fixed with ISO time format update <https://github.com/SNEWS2/SNEWS_Publishing_Tools/commit/89acd9097dcdac01e27e09f5b0ce87a41e842575>
