### ISSUE TITLE
nested method 

### ISSUE THREAD

**Issue by Storreslara** [SNEWS2/SNEWS_Publishing_Tools#28]
Shouldn't this method be defined in the class rather than defined inside `tier_decider` . Every time `tier_decider` is called append message will be redefined. Seems inefficient 

https://github.com/SNEWS2/SNEWS_Publishing_Tools/blob/40301467bfd1df011e470f201361f5d3acbd0a79/SNEWS_PT/snews_pt_utils.py#L289

**Comment by KaraMelih** [comment]
Right, actually that function uses several more arguments like `data`, `meta`, `schema` and function itself is used several times _within_ the `_tier_decider` so once the tier decider is called, `_append_messages` is also defined once, and until it appends all the messages it uses these data, meta, schema from the "global" (well, it is local to `_append_messages`) so I thought this may even be more efficient
