### ISSUE TITLE
yield message

### ISSUE THREAD

**Issue by KaraMelih** [SNEWS2/SNEWS_Publishing_Tools#32]
Here https://github.com/SNEWS2/SNEWS_Publishing_Tools/blob/181ed533dbc5768b203f88d609c5954e68a6250e/SNEWS_PT/snews_sub.py#L97 we can `yield` the alert message therefore, it can be picked by other scripts. `yield` allows for returning a value without terminating the command.

We can read it here https://github.com/SNEWS2/SNEWS_Publishing_Tools/blob/181ed533dbc5768b203f88d609c5954e68a6250e/SNEWS_PT/__main__.py#L70 and allow for passing the output to other scripts. i.e. it would be something like;

```python
@main.command()
@click.option('--plugin','-p', type='str', default="None")
@click.pass_context
def subscribe(ctx, plugin):
    """ Subscribe to Alert topic
    """
    sub = Subscriber(ctx.obj['env'])
    try:
        alert_message = sub.subscribe()
       if plugin != "None":
           os.system(f"python {plugin} {alert_message}")
    except KeyboardInterrupt:
        pass
```
Therefore, any `plugin` script can be given and the alert content is redirected

**Comment by KaraMelih** [comment]
In 4d994e71828762ea6a03f19decf36c0035c606cb I added this but cannot test it yet. I had to update the conda... need a few hours

**Comment by justinvasel** [comment]
This appears to have been addressed through the aforementioned commit. Closing the issue.
