### ISSUE TITLE
no-auth option

### ISSUE THREAD

**Issue by KaraMelih** [SNEWS2/SNEWS_Publishing_Tools#36]
For publishing we have `auth=True` option

Should we check if the user has hop credentials (`hop auth locate` we can even grab the username if the authentication file exists), and if they do not have the credentials we raise a warning first and default to `auth=False` in publisher. Or do we only want people with credentials to test the tools? (or that they know they don't have credentials and manually set `auth=False` ? )

For subscription, we do not have an `auth` option at all. Maybe at least there we should check this and say "yo, you don't have permission to subscribe, go check your hop credentials"

**Comment by joesmolsky** [comment]
Khafka has said they only want authorized messages to be published.  I'll close the issue but it can be re-opened if someone thinks we need no-auth subscriptions.
