### ISSUE TITLE
Significance and coincidence tier separation

### ISSUE THREAD

**Issue by joesmolsky** [SNEWS2/SNEWS_Publishing_Tools#50]
Significance tier messages are sent to significance and coincidence tier.  They should only be sent to significance and not coincidence.

**Comment by KaraMelih** [comment]
Could you show an example? 
As per these lines https://github.com/SNEWS2/SNEWS_Publishing_Tools/blob/6c7d5bd0368c231cd13d5f8a884f7f9769277769/snews_pt/snews_pt_utils.py#L333-L339

if it has both `'neutrino_time'` and `'p_values'` this is the expected behaviour
