### ISSUE TITLE
Test-connection echo

### ISSUE THREAD

**Issue by joesmolsky** [SNEWS2/SNEWS_Publishing_Tools#53]
When I run `snews_pt test-connection` I get the following echo:

```shell
/Users/joe/src/gitjoe/SNEWS_Publishing_Tools/snews_pt/__init__.py:23: UserWarning: You are using default detector name "TEST"
Please change this by snews_pt.snews_pt_utils.set_name()
  warnings.warn(warning_text, UserWarning)
Testing your connection to kafka://kafka.scimma.org/snews.experiments-firedrill.
 Should take 4-5 seconds...
```

The test takes about 4-5 seconds, but I do not receive an echo indicating the success or failure of the test.

**Comment by KaraMelih** [comment]
can you try passing `-s 6` this should indicate, how many messages in the past it should be looking for

**Comment by joesmolsky** [comment]
I tried with it with `-s 6` and `--no-firedrill`.  It does not change the output.

**Comment by joesmolsky** [comment]
Fixed by commit <https://github.com/SNEWS2/SNEWS_Publishing_Tools/commit/b5238789ded85efe427b3fe3bb1d43a54a93a378>
