### ISSUE TITLE
review project documentation

### ISSUE THREAD

**Issue by sybenzvi** [SNEWS2/SNEWS_Publishing_Tools#71]
Review `snews_pt` project documentation, after @KaraMelih's suggestion in the [LNGS hackathon coordination doc](https://docs.google.com/document/d/1te0yDkxDC0ZXcHjF21vKPbp7fT0E4f70p_Z62y0Gdjw/edit?usp=sharing). Preliminary checklist:
- [x] Check top-level READMEs to ensure consistent instructions.
- [x] Check readthedocs to make sure installation and usage examples are consistent and useful.
- [x] Ensure notebooks and example scripts are properly documented.
- [x] Revisit docstrings and make sure they are consistent with module contents.

**Comment by KaraMelih** [comment]
Mostly addressed in #79 except for the individual docstrings. I can start on that now.
