### ISSUE TITLE
flesh out the SNEWS 2.0 alert system technical paper

### ISSUE THREAD

**Issue by sybenzvi** [SNEWS2/SNEWS_Publishing_Tools#72]
Fill in missing plots and text in the technical paper draft being prepared for submission JINST.

Current working title is: T**he SNEWS 2.0 Alert System for the Coincident Detection of Neutrinos from Core-Collapse Supernovae**.

@habig can give write access if needed.

**Comment by justinvasel** [comment]
Congratulations on the release of this great paper!
