### ISSUE TITLE
Use relative timing for timing tier messages

### ISSUE THREAD

**Issue by habig** [SNEWS2/SNEWS_Publishing_Tools#83]
Currently an experiment calls snews_pt to submit an alert.  The first neutrino time is called the burst time and is what's sent in the coincidence tier message.  If there's also a timing_series in there, a timing tier message is also sent.  Great, one stop shopping for the experiments.

However, this will generate a lot of timestamp objects, which differ only in the last few significant figures, as the burst is lasting seconds not years.

Proposal: the timestamp objects are replaced with floats that are the relative time (in seconds) from the initial time.

**Comment by KaraMelih** [comment]
I think this is solved with this #98 PR. Closing for now, we can re-open again if we think something is still missing
