### ISSUE TITLE
documentation & unit tests & deployment

### ISSUE THREAD

**Issue by KaraMelih** [SNEWS2/SNEWS_Publishing_Tools#9]
We need to write documentation for all the functions & classes, and also readme for the repo, preferably a detailed tutorial. Also, we need to write a _readthedocs_ file, this can be copied from `SN_alert_app` repo and modified. <br>

Simple unit tests, and slightly fancier connection tests e.g. `is server alive` need to be written. <br>

We need to deploy to somewhere like [pypi](https://pypi.org/)

**Comment by KaraMelih** [comment]
The docs for SN_alert_app [was like this](https://github.com/SNEWS2/hop-SNalert-app/tree/snews2_dev/doc) we can modify it from there. I can copy those here and we can start filling in<br>

We still need proper tests. @joesmolsky @Storreslara any volunteer?

**Comment by joesmolsky** [comment]
I can work on testing.

**Comment by KaraMelih** [comment]
continuos progress. We have a structure. Closing the issue.
